### ISSUE TITLE
Code not displayed in XD on Windows

### ISSUE THREAD

**Issue by at48fps** [stursby/xd-copy-svg-code-plugin#5]
Hi there,

I've been trying to get this SVG Code generator plugin but its not working for me on Adobe XD for Windows.
When I create a shape (SQUARE) and go to Menu>Plugins>Copy SVG Code, the resulting dialog box does not have any content in the text box. Then, when I apply this plugin to another shape (CIRCLE), the text box is empty once again, however this time, the SVG code of the previous shape (SQUARE) has been added in my clipboard and I can paste that there. I'm sure from the documentation that it should not work that way, and instead display the SVG Code for the SQUARE in the text box when I apply the plugin to the SQUARE. Hope I was clear enough. Please look into this issue. This plugin seems handy to me and would love to continue to use it.

I have Win 10 v1803 and my XD version is 13.1.32.8.

**Comment by at48fps** [comment]
So I did some checking, and turns out that (apart from not displaying the code in the text box) the SVG code is getting copied to my clipboard AFTER I click on the CLOSE button, not before it.

You could fix the code display issue, as well as add a COPY CODE button the to dialog box. Clicking this button would copy the code to the clipboard and close the dialog box and display a toast 'code copied successfully' toast. Just some friendly suggestions. :)

**Comment by wgstjf** [comment]
We're seeing the same issue here on Windows 10 and XD v.20.  Did you manage to do any Windows-based tests?

**Comment by stursby** [comment]
@wgstjf No, I haven't had time to test on a Windows machine, sorry. Are you able to clone the repo and run the plugin locally and see if there's a good workaround/fix?

**Comment by wgstjf** [comment]
Not a bad plan, though like yourself time is always the issue :-)  Will try to make time this week to investigate.  Cheers

**Comment by wgstjf** [comment]
Ok, so had a quick play and the issue seems to be that textareas can't have a value passed to them (in Windows).  If we change the template to use an input (text) field then the value is properly set/displayed.  

Additionally, moving the clipboard stuff above the dialogue creation ensures the code gets copied to the clipboard without having to click the 'Close button'

The following is the modified from line 41 of src/main.js

```js
// Read tmp file and generate SVG code
  const markup = await file.read()
  const svgCode = escapeHtml(markup)
  // Copy to clipboard too!
  clipboard.copyText(markup)  // Moved to before createDialog to fix issues on Windows
  // Show output dialog
  await createDialog({
    title: 'SVG Output',
    //template: () => `<textarea>${svgCode}</textarea>` // This doesn't work
    template: () => `<input value="${svgCode}">` // This works
  })
```
The following shows the code being properly output to the input field:

![copy-svg-code-2](https://user-images.githubusercontent.com/3740694/59856719-6532ed00-936f-11e9-8d7e-a134badd9f0b.gif)

Not great with github but for what it's worth here's my fork showing the modifications: https://github.com/wgstjf/xd-copy-svg-code-plugin

Either way I hope it's of some help.

Cheers,

Will

**Comment by stursby** [comment]
@wgstjf Sweet! Thanks for digging in, feel free to submit a PR otherwise I can go ahead and make the changes.

**Comment by wgstjf** [comment]
Wouldn't know how to :-)  Do go ahead with the changes (assuming all's working fine on Mac).

**Comment by stursby** [comment]
@wgstjf Updated! Version `1.0.3` is now under review by Adobe. Thanks for your help 🙌🏻

**Comment by wgstjf** [comment]
No worries and thanks for getting the new version out so quickly.

**Comment by stursby** [comment]
Hey @wgstjf, version `1.0.3` was approved this morning. You should be able to install it via XD now.

![image](https://user-images.githubusercontent.com/527849/60029278-75e0ad00-9666-11e9-9e58-125f40a6e48f.png)

Could you update to `1.0.3` and confirm that it's working on Windows?
